version: "3.2"
services:
  # prisma:
  #   image: prismagraphql/prisma:1.34
  #   restart: always
  #   ports:
  #     - "4470:4466"
  #   environment:
  #     PRISMA_CONFIG: |
  #       port: 4466
  #       # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
  #       # managementApiSecret: my-secret
  #       databases:
  #         test:
  #           connector: mysql
  #           host: mysql
  #           user: root
  #           password: wMT9ABAAmyrju3wF
  #           rawAccess: true
  #           port: 3306
  #           migrations: true
  #         default:
  #           connector: mysql
  #           host: mysql
  #           user: root
  #           password: wMT9ABAAmyrju3wF
  #           rawAccess: true
  #           port: 3370
  #           migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
    ports:
      - "3370:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wMT9ABAAmyrju3wF
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin_gracebank
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PORT=3306
      - PMA_PASSWORD=wMT9ABAAmyrju3wF
    links:
      - mysql
    ports:
      - 8870:80

volumes:
  mysql:
